/* Generated by port/tools/gen_host_command_layout.py from
 * src/melee/lb/types.h; do not edit.
 *
 * The host converts the words of a command stream to native order, and
 * these declarations put every field on the bits MWCC gives it: the
 * fields of each word in reverse order, with unnamed padding where the
 * console leaves bits unused.  A pointer in a stream is `rel`, the
 * distance from its own word to the target. */

#ifndef MELEE_HOST_COMMAND_LAYOUT_H
#define MELEE_HOST_COMMAND_LAYOUT_H

union ColorOverlay_x8_t {
    struct {
        u32 a : 8;
        u32 b : 8;
        u32 g : 8;
        u32 r : 8;
    } light_color;
    struct {
        s32 yz : 13;
        s32 x : 13;
        s32 unk : 6;
    } light_rot1;
    struct {
        s32 yz : 12;
        s32 x : 12;
        u32 x0_7 : 1;
        u32 light_enable : 1;
        u32 x0_5 : 1;
        u32 x0_4 : 1;
        u32 x0_3 : 1;
        u32 x0_2 : 1;
        u32 x0_1 : 1;
        u32 x0_0 : 1;
    } light_rot2;
    struct {
        u32 timer : 26;
        u32 unk : 6;
    } unk;
};

struct Command_00 {
    u32 value : 26;
    u32 code : 6;
};
_Static_assert(sizeof(struct Command_00) == 4, "Command_00");

struct Command_02 {
    u32 value : 26;
    u32 code : 6;
};
_Static_assert(sizeof(struct Command_02) == 4, "Command_02");

struct Command_03 {
    u32 value : 26;
    u32 code : 6;
};
_Static_assert(sizeof(struct Command_03) == 4, "Command_03");

struct Command_04 {
    u32 x;
};
_Static_assert(sizeof(struct Command_04) == 4, "Command_04");

struct Command_05 {
    s32 rel; /* ptr: target - &rel */
};
_Static_assert(sizeof(struct Command_05) == 4, "Command_05");

struct Command_07 {
    s32 rel; /* ptr: target - &rel */
};
_Static_assert(sizeof(struct Command_07) == 4, "Command_07");

struct Command_09 {
    u32 param_2 : 18;
    u32 param_1 : 8;
    u32 id : 6;
};
_Static_assert(sizeof(struct Command_09) == 4, "Command_09");

struct unk0 {
    u32 unk2 : 18;
    u32 unk1 : 8;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk0) == 4, "unk0");

struct unk1 {
    u32 : 19;
    u32 unk2 : 1;
    u32 unk1 : 4;
    u32 unk0 : 2;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk1) == 4, "unk1");

struct set_throw_flags {
    u32 hit_idx : 26;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_throw_flags) == 4, "set_throw_flags");

struct unk3 {
    s32 unk1 : 25;
    s32 unk0 : 7;
};
_Static_assert(sizeof(struct unk3) == 4, "unk3");

struct unk4 {
    u32 : 18;
    u32 unk1 : 8;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk4) == 4, "unk4");

struct unk5 {
    s32 unk1 : 18;
    s32 unk0 : 14;
};
_Static_assert(sizeof(struct unk5) == 4, "unk5");

struct unk6 {
    u32 : 25;
    u32 unk1 : 1;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk6) == 4, "unk6");

struct set_airborne_state {
    u32 state : 26;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_airborne_state) == 4, "set_airborne_state");

struct unk8 {
    int unk0;
};
_Static_assert(sizeof(struct unk8) == 4, "unk8");

struct part_anim {
    u32 unk3 : 12;
    s32 unk2 : 7;
    s32 unk1 : 7;
    s32 opcode : 6;
};
_Static_assert(sizeof(struct part_anim) == 4, "part_anim");

struct unk9 {
    u32 unk2 : 13;
    u32 unk1 : 13;
    s32 unk0 : 6;
};
_Static_assert(sizeof(struct unk9) == 4, "unk9");

struct unk10 {
    u32 unk3 : 13;
    u32 unk2 : 12;
    u32 unk1 : 1;
    s32 unk0 : 6;
};
_Static_assert(sizeof(struct unk10) == 4, "unk10");

struct unk11 {
    u32 unk1 : 26;
    s32 unk0 : 6;
};
_Static_assert(sizeof(struct unk11) == 4, "unk11");

struct unk12 {
    u32 unk3 : 14;
    u32 unk2 : 10;
    u32 unk1 : 2;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk12) == 4, "unk12");

struct unk13 {
    u32 unk2 : 18;
    u32 unk1 : 8;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk13) == 4, "unk13");

struct unk14 {
    u32 : 18;
    u32 unk1 : 8;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk14) == 4, "unk14");

struct unk15 {
    u32 unk1 : 26;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk15) == 4, "unk15");

struct unk16 {
    s32 unk4 : 25;
    s32 unk3 : 1;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk16) == 4, "unk16");

struct unk17 {
    s32 unk1 : 26;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk17) == 4, "unk17");

struct unk18 {
    s32 damage_amount : 26;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk18) == 4, "unk18");

struct unk19 {
    u32 unk1 : 26;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk19) == 4, "unk19");

struct unk20 {
    u32 unk1 : 26;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk20) == 4, "unk20");

struct unk21 {
    u32 : 17;
    u32 unk2 : 8;
    u32 unk1 : 1;
    u32 unk0 : 6;
};
_Static_assert(sizeof(struct unk21) == 4, "unk21");

struct set_hitbox_damage {
    u32 value : 23;
    u32 idx : 3;
    u32 opcdoe : 6;
};
_Static_assert(sizeof(struct set_hitbox_damage) == 4, "set_hitbox_damage");

struct set_hitbox_scale {
    u32 value : 23;
    u32 idx : 3;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_hitbox_scale) == 4, "set_hitbox_scale");

struct set_hitbox_x42_b57 {
    u32 value : 1;
    u32 type : 1;
    u32 idx : 24;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_hitbox_x42_b57) == 4, "set_hitbox_x42_b57");

struct set_cmd_var {
    u32 value : 24;
    u32 idx : 2;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_cmd_var) == 4, "set_cmd_var");

struct set_hurt_state {
    u32 state : 18;
    u32 bone_idx : 8;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_hurt_state) == 4, "set_hurt_state");

struct set_jab_combo {
    u32 disabled : 26;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_jab_combo) == 4, "set_jab_combo");

struct set_jab_rapid {
    u32 state : 26;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_jab_rapid) == 4, "set_jab_rapid");

struct set_dobj_flags {
    s32 value : 19;
    s32 idx : 7;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_dobj_flags) == 4, "set_dobj_flags");

struct set_throw_hitbox_0 {
    u32 damage : 23;
    u32 idx : 3;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_throw_hitbox_0) == 4, "set_throw_hitbox_0");

struct set_throw_hitbox_1 {
    u32 : 5;
    u32 hit_x28 : 9;
    u32 hit_x24 : 9;
    u32 unk0 : 9;
};
_Static_assert(sizeof(struct set_throw_hitbox_1) == 4, "set_throw_hitbox_1");

struct set_throw_hitbox_2 {
    u32 : 12;
    u32 sfx_kind : 4;
    u32 sfx_severity : 3;
    u32 element : 4;
    u32 hit_x2C : 9;
};
_Static_assert(sizeof(struct set_throw_hitbox_2) == 4, "set_throw_hitbox_2");

struct unk27 {
    u32 value : 26;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk27) == 4, "unk27");

struct set_article_vis {
    u32 value : 26;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_article_vis) == 4, "set_article_vis");

struct set_fighter_vis {
    u32 value : 26;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_fighter_vis) == 4, "set_fighter_vis");

struct set_tex_anim {
    s32 frame : 11;
    s32 idx2 : 7;
    s32 idx : 7;
    u32 b : 1;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct set_tex_anim) == 4, "set_tex_anim");

struct unk31 {
    u32 unk1 : 16;
    u32 unk0 : 10;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk31) == 4, "unk31");

struct unk32 {
    u32 unk1 : 13;
    u32 unk0 : 13;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk32) == 4, "unk32");

struct unk33 {
    u32 unk1 : 13;
    u32 unk0 : 13;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk33) == 4, "unk33");

struct spawn_gfx_0 {
    u32 unk1 : 15;
    u32 useUnkBone : 1;
    u32 destroyOnStateChange : 1;
    u32 useCommonBoneIDs : 1;
    u32 boneId : 8;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct spawn_gfx_0) == 4, "spawn_gfx_0");

struct spawn_gfx_1 {
    u32 unkFloat : 16;
    u32 gfxID : 16;
};
_Static_assert(sizeof(struct spawn_gfx_1) == 4, "spawn_gfx_1");

struct spawn_gfx_2 {
    s32 offsetY : 16;
    s32 offsetZ : 16;
};
_Static_assert(sizeof(struct spawn_gfx_2) == 4, "spawn_gfx_2");

struct spawn_gfx_3 {
    u32 rangeZ : 16;
    s32 offsetX : 16;
};
_Static_assert(sizeof(struct spawn_gfx_3) == 4, "spawn_gfx_3");

struct spawn_gfx_4 {
    u32 rangeX : 16;
    u32 rangeY : 16;
};
_Static_assert(sizeof(struct spawn_gfx_4) == 4, "spawn_gfx_4");

struct spawn_hitbox_0 {
    u32 damage : 10;
    u32 use_common_bone_ids : 1;
    u32 bone : 8;
    u32 only_hit_grabbed : 1;
    u32 hit_group : 3;
    u32 id : 3;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct spawn_hitbox_0) == 4, "spawn_hitbox_0");

struct spawn_hitbox_1 {
    s32 z_offset : 16;
    u32 size : 16;
};
_Static_assert(sizeof(struct spawn_hitbox_1) == 4, "spawn_hitbox_1");

struct spawn_hitbox_2 {
    s32 x_offset : 16;
    s32 y_offset : 16;
};
_Static_assert(sizeof(struct spawn_hitbox_2) == 4, "spawn_hitbox_2");

struct spawn_hitbox_3 {
    u32 rebound : 1;
    u32 clank : 1;
    u32 ignore_fighter_scale : 1;
    u32 ignore_thrown_fighters : 1;
    u32 item_hit_interaction : 1;
    u32 weight_set_knockback : 9;
    u32 knockback_growth : 9;
    u32 angle : 9;
};
_Static_assert(sizeof(struct spawn_hitbox_3) == 4, "spawn_hitbox_3");

struct spawn_hitbox_4 {
    u32 hit_aerial : 1;
    u32 hit_grounded : 1;
    u32 hit_sfx_kind : 5;
    u32 hit_sfx_severity : 3;
    s32 shield_damage : 8;
    u32 element : 5;
    u32 base_knockback : 9;
};
_Static_assert(sizeof(struct spawn_hitbox_4) == 4, "spawn_hitbox_4");

struct spawn_hitbox_5 {
    u32 : 16;
    u32 x1_b7 : 1;
    u32 x1_b6 : 1;
    u32 x1_b5 : 1;
    u32 x1_b4 : 1;
    u32 x1_b3 : 1;
    u32 x1_b2 : 1;
    u32 x1_b1 : 1;
    u32 x1_b0 : 1;
    u32 x0 : 8;
};
_Static_assert(sizeof(struct spawn_hitbox_5) == 4, "spawn_hitbox_5");

struct it_create_hitbox_0 {
    u32 damage : 13;
    u32 bone : 7;
    u32 hit_group : 3;
    u32 id : 3;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct it_create_hitbox_0) == 4, "it_create_hitbox_0");

struct it_create_hitbox_4 {
    u32 x40_b2 : 1;
    u32 x40_b3 : 1;
    u32 sfx_kind : 4;
    u32 sfx_severity : 3;
    s32 shield_damage : 8;
    u32 x40_b0 : 1;
    u32 element : 5;
    u32 base_knockback : 9;
};
_Static_assert(sizeof(struct it_create_hitbox_4) == 4, "it_create_hitbox_4");

struct spawn_hitbox_skip {
    u8 _0[12];
    u32 : 3;
    u32 xF_b4 : 1;
    u32 xF_b3 : 1;
    u32 xF_b2 : 1;
    u32 xF_b1 : 1;
    u32 xF_b0 : 1;
    u32 : 24;
};
_Static_assert(sizeof(struct spawn_hitbox_skip) == 16, "spawn_hitbox_skip");

struct sound_effect_0 {
    u32 unknown : 18;
    u32 behavior : 8;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct sound_effect_0) == 4, "sound_effect_0");

struct sound_effect_1 {
    u32 sfx_id;
};
_Static_assert(sizeof(struct sound_effect_1) == 4, "sound_effect_1");

struct sound_effect_2 {
    u32 panning : 8;
    u32 volume : 8;
    u32 padding : 16;
};
_Static_assert(sizeof(struct sound_effect_2) == 4, "sound_effect_2");

struct pseudo_random_sfx_0 {
    u32 random_range : 6;
    u32 behavior : 4;
    u32 panning : 8;
    u32 volume : 8;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct pseudo_random_sfx_0) == 4, "pseudo_random_sfx_0");

struct pseudo_random_sfx_1 {
    u32 sfx_id;
};
_Static_assert(sizeof(struct pseudo_random_sfx_1) == 4, "pseudo_random_sfx_1");

struct stage_sfx_0 {
    u32 pitch_select : 8;
    u32 x2_b0_7 : 8;
    u32 sfx_base : 10;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct stage_sfx_0) == 4, "stage_sfx_0");

struct stage_sfx_1 {
    u32 sfx_id;
};
_Static_assert(sizeof(struct stage_sfx_1) == 4, "stage_sfx_1");

struct stage_sfx_2 {
    u32 x2_b0_15 : 16;
    u32 x0_b0_15 : 16;
};
_Static_assert(sizeof(struct stage_sfx_2) == 4, "stage_sfx_2");

struct stage_sfx_3 {
    u32 x3_b0_7 : 8;
    u32 x2_b0_7 : 8;
    u32 x0_b0_15 : 16;
};
_Static_assert(sizeof(struct stage_sfx_3) == 4, "stage_sfx_3");

struct footstep_fx_0 {
    u32 x3_b0_7 : 8;
    u32 x2_b0_7 : 8;
    u32 x1_b7 : 1;
    u32 use_alt_bone : 1;
    u32 boneId : 8;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct footstep_fx_0) == 4, "footstep_fx_0");

struct unk_fx_0 {
    u32 x3_b0_7 : 8;
    u32 x2_b0_7 : 8;
    u32 x1_b0_7 : 8;
    u32 x0_b6_7 : 2;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct unk_fx_0) == 4, "unk_fx_0");

struct smash_charge_0 {
    u32 charge_rate : 16;
    u32 charge_frames : 10;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct smash_charge_0) == 4, "smash_charge_0");

struct smash_charge_1 {
    u32 x1_b0_23 : 24;
    u32 color_anim : 8;
};
_Static_assert(sizeof(struct smash_charge_1) == 4, "smash_charge_1");

struct wind_fx_0 {
    u32 bone : 8;
    u32 x0_b6_17 : 18;
    u32 opcode : 6;
};
_Static_assert(sizeof(struct wind_fx_0) == 4, "wind_fx_0");

struct wind_fx_1 {
    s32 x : 16;
    s32 timer : 16;
};
_Static_assert(sizeof(struct wind_fx_1) == 4, "wind_fx_1");

struct wind_fx_2 {
    s32 mag : 16;
    s32 y : 16;
};
_Static_assert(sizeof(struct wind_fx_2) == 4, "wind_fx_2");

struct wind_fx_3 {
    s32 decay : 16;
    s32 angle : 16;
};
_Static_assert(sizeof(struct wind_fx_3) == 4, "wind_fx_3");

#endif
