/* Generated by port/tools/gen_host_command_layout.py; do not edit.
 *
 * Packs values into words where MWCC lays each field out and reads them
 * back through the host declarations of port/src/game/host_command_layout.h. */

#include <melee/lb/types.h>

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

typedef int64_t (*CommandFieldGetter)(const uint32_t* words);

typedef struct CommandFieldCase {
    const char* name;
    unsigned word;
    unsigned lsb;
    unsigned width;
    int is_signed;
    CommandFieldGetter get;
} CommandFieldCase;

static int64_t get_0(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_color.r;
}

static int64_t get_1(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_color.g;
}

static int64_t get_2(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_color.b;
}

static int64_t get_3(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_color.a;
}

static int64_t get_4(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot1.unk;
}

static int64_t get_5(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot1.x;
}

static int64_t get_6(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot1.yz;
}

static int64_t get_7(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x0_0;
}

static int64_t get_8(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x0_1;
}

static int64_t get_9(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x0_2;
}

static int64_t get_10(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x0_3;
}

static int64_t get_11(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x0_4;
}

static int64_t get_12(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x0_5;
}

static int64_t get_13(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.light_enable;
}

static int64_t get_14(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x0_7;
}

static int64_t get_15(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.x;
}

static int64_t get_16(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->light_rot2.yz;
}

static int64_t get_17(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->unk.unk;
}

static int64_t get_18(const uint32_t* words)
{
    return ((const union ColorOverlay_x8_t*) (const void*) words)->unk.timer;
}

static int64_t get_19(const uint32_t* words)
{
    return ((const struct Command_00*) (const void*) words)->code;
}

static int64_t get_20(const uint32_t* words)
{
    return ((const struct Command_00*) (const void*) words)->value;
}

static int64_t get_21(const uint32_t* words)
{
    return ((const struct Command_02*) (const void*) words)->code;
}

static int64_t get_22(const uint32_t* words)
{
    return ((const struct Command_02*) (const void*) words)->value;
}

static int64_t get_23(const uint32_t* words)
{
    return ((const struct Command_03*) (const void*) words)->code;
}

static int64_t get_24(const uint32_t* words)
{
    return ((const struct Command_03*) (const void*) words)->value;
}

static int64_t get_25(const uint32_t* words)
{
    return ((const struct Command_04*) (const void*) words)->x;
}

static int64_t get_26(const uint32_t* words)
{
    return ((const struct Command_09*) (const void*) words)->id;
}

static int64_t get_27(const uint32_t* words)
{
    return ((const struct Command_09*) (const void*) words)->param_1;
}

static int64_t get_28(const uint32_t* words)
{
    return ((const struct Command_09*) (const void*) words)->param_2;
}

static int64_t get_29(const uint32_t* words)
{
    return ((const struct unk0*) (const void*) words)->opcode;
}

static int64_t get_30(const uint32_t* words)
{
    return ((const struct unk0*) (const void*) words)->unk1;
}

static int64_t get_31(const uint32_t* words)
{
    return ((const struct unk0*) (const void*) words)->unk2;
}

static int64_t get_32(const uint32_t* words)
{
    return ((const struct unk1*) (const void*) words)->opcode;
}

static int64_t get_33(const uint32_t* words)
{
    return ((const struct unk1*) (const void*) words)->unk0;
}

static int64_t get_34(const uint32_t* words)
{
    return ((const struct unk1*) (const void*) words)->unk1;
}

static int64_t get_35(const uint32_t* words)
{
    return ((const struct unk1*) (const void*) words)->unk2;
}

static int64_t get_36(const uint32_t* words)
{
    return ((const struct set_throw_flags*) (const void*) words)->opcode;
}

static int64_t get_37(const uint32_t* words)
{
    return ((const struct set_throw_flags*) (const void*) words)->hit_idx;
}

static int64_t get_38(const uint32_t* words)
{
    return ((const struct unk3*) (const void*) words)->unk0;
}

static int64_t get_39(const uint32_t* words)
{
    return ((const struct unk3*) (const void*) words)->unk1;
}

static int64_t get_40(const uint32_t* words)
{
    return ((const struct unk4*) (const void*) words)->opcode;
}

static int64_t get_41(const uint32_t* words)
{
    return ((const struct unk4*) (const void*) words)->unk1;
}

static int64_t get_42(const uint32_t* words)
{
    return ((const struct unk5*) (const void*) words)->unk0;
}

static int64_t get_43(const uint32_t* words)
{
    return ((const struct unk5*) (const void*) words)->unk1;
}

static int64_t get_44(const uint32_t* words)
{
    return ((const struct unk6*) (const void*) words)->opcode;
}

static int64_t get_45(const uint32_t* words)
{
    return ((const struct unk6*) (const void*) words)->unk1;
}

static int64_t get_46(const uint32_t* words)
{
    return ((const struct set_airborne_state*) (const void*) words)->opcode;
}

static int64_t get_47(const uint32_t* words)
{
    return ((const struct set_airborne_state*) (const void*) words)->state;
}

static int64_t get_48(const uint32_t* words)
{
    return ((const struct unk8*) (const void*) words)->unk0;
}

static int64_t get_49(const uint32_t* words)
{
    return ((const struct part_anim*) (const void*) words)->opcode;
}

static int64_t get_50(const uint32_t* words)
{
    return ((const struct part_anim*) (const void*) words)->unk1;
}

static int64_t get_51(const uint32_t* words)
{
    return ((const struct part_anim*) (const void*) words)->unk2;
}

static int64_t get_52(const uint32_t* words)
{
    return ((const struct part_anim*) (const void*) words)->unk3;
}

static int64_t get_53(const uint32_t* words)
{
    return ((const struct unk9*) (const void*) words)->unk0;
}

static int64_t get_54(const uint32_t* words)
{
    return ((const struct unk9*) (const void*) words)->unk1;
}

static int64_t get_55(const uint32_t* words)
{
    return ((const struct unk9*) (const void*) words)->unk2;
}

static int64_t get_56(const uint32_t* words)
{
    return ((const struct unk10*) (const void*) words)->unk0;
}

static int64_t get_57(const uint32_t* words)
{
    return ((const struct unk10*) (const void*) words)->unk1;
}

static int64_t get_58(const uint32_t* words)
{
    return ((const struct unk10*) (const void*) words)->unk2;
}

static int64_t get_59(const uint32_t* words)
{
    return ((const struct unk10*) (const void*) words)->unk3;
}

static int64_t get_60(const uint32_t* words)
{
    return ((const struct unk11*) (const void*) words)->unk0;
}

static int64_t get_61(const uint32_t* words)
{
    return ((const struct unk11*) (const void*) words)->unk1;
}

static int64_t get_62(const uint32_t* words)
{
    return ((const struct unk12*) (const void*) words)->unk0;
}

static int64_t get_63(const uint32_t* words)
{
    return ((const struct unk12*) (const void*) words)->unk1;
}

static int64_t get_64(const uint32_t* words)
{
    return ((const struct unk12*) (const void*) words)->unk2;
}

static int64_t get_65(const uint32_t* words)
{
    return ((const struct unk12*) (const void*) words)->unk3;
}

static int64_t get_66(const uint32_t* words)
{
    return ((const struct unk13*) (const void*) words)->unk0;
}

static int64_t get_67(const uint32_t* words)
{
    return ((const struct unk13*) (const void*) words)->unk1;
}

static int64_t get_68(const uint32_t* words)
{
    return ((const struct unk13*) (const void*) words)->unk2;
}

static int64_t get_69(const uint32_t* words)
{
    return ((const struct unk14*) (const void*) words)->unk0;
}

static int64_t get_70(const uint32_t* words)
{
    return ((const struct unk14*) (const void*) words)->unk1;
}

static int64_t get_71(const uint32_t* words)
{
    return ((const struct unk15*) (const void*) words)->unk0;
}

static int64_t get_72(const uint32_t* words)
{
    return ((const struct unk15*) (const void*) words)->unk1;
}

static int64_t get_73(const uint32_t* words)
{
    return ((const struct unk16*) (const void*) words)->unk0;
}

static int64_t get_74(const uint32_t* words)
{
    return ((const struct unk16*) (const void*) words)->unk3;
}

static int64_t get_75(const uint32_t* words)
{
    return ((const struct unk16*) (const void*) words)->unk4;
}

static int64_t get_76(const uint32_t* words)
{
    return ((const struct unk17*) (const void*) words)->unk0;
}

static int64_t get_77(const uint32_t* words)
{
    return ((const struct unk17*) (const void*) words)->unk1;
}

static int64_t get_78(const uint32_t* words)
{
    return ((const struct unk18*) (const void*) words)->unk0;
}

static int64_t get_79(const uint32_t* words)
{
    return ((const struct unk18*) (const void*) words)->damage_amount;
}

static int64_t get_80(const uint32_t* words)
{
    return ((const struct unk19*) (const void*) words)->unk0;
}

static int64_t get_81(const uint32_t* words)
{
    return ((const struct unk19*) (const void*) words)->unk1;
}

static int64_t get_82(const uint32_t* words)
{
    return ((const struct unk20*) (const void*) words)->unk0;
}

static int64_t get_83(const uint32_t* words)
{
    return ((const struct unk20*) (const void*) words)->unk1;
}

static int64_t get_84(const uint32_t* words)
{
    return ((const struct unk21*) (const void*) words)->unk0;
}

static int64_t get_85(const uint32_t* words)
{
    return ((const struct unk21*) (const void*) words)->unk1;
}

static int64_t get_86(const uint32_t* words)
{
    return ((const struct unk21*) (const void*) words)->unk2;
}

static int64_t get_87(const uint32_t* words)
{
    return ((const struct set_hitbox_damage*) (const void*) words)->opcdoe;
}

static int64_t get_88(const uint32_t* words)
{
    return ((const struct set_hitbox_damage*) (const void*) words)->idx;
}

static int64_t get_89(const uint32_t* words)
{
    return ((const struct set_hitbox_damage*) (const void*) words)->value;
}

static int64_t get_90(const uint32_t* words)
{
    return ((const struct set_hitbox_scale*) (const void*) words)->opcode;
}

static int64_t get_91(const uint32_t* words)
{
    return ((const struct set_hitbox_scale*) (const void*) words)->idx;
}

static int64_t get_92(const uint32_t* words)
{
    return ((const struct set_hitbox_scale*) (const void*) words)->value;
}

static int64_t get_93(const uint32_t* words)
{
    return ((const struct set_hitbox_x42_b57*) (const void*) words)->opcode;
}

static int64_t get_94(const uint32_t* words)
{
    return ((const struct set_hitbox_x42_b57*) (const void*) words)->idx;
}

static int64_t get_95(const uint32_t* words)
{
    return ((const struct set_hitbox_x42_b57*) (const void*) words)->type;
}

static int64_t get_96(const uint32_t* words)
{
    return ((const struct set_hitbox_x42_b57*) (const void*) words)->value;
}

static int64_t get_97(const uint32_t* words)
{
    return ((const struct set_cmd_var*) (const void*) words)->opcode;
}

static int64_t get_98(const uint32_t* words)
{
    return ((const struct set_cmd_var*) (const void*) words)->idx;
}

static int64_t get_99(const uint32_t* words)
{
    return ((const struct set_cmd_var*) (const void*) words)->value;
}

static int64_t get_100(const uint32_t* words)
{
    return ((const struct set_hurt_state*) (const void*) words)->opcode;
}

static int64_t get_101(const uint32_t* words)
{
    return ((const struct set_hurt_state*) (const void*) words)->bone_idx;
}

static int64_t get_102(const uint32_t* words)
{
    return ((const struct set_hurt_state*) (const void*) words)->state;
}

static int64_t get_103(const uint32_t* words)
{
    return ((const struct set_jab_combo*) (const void*) words)->opcode;
}

static int64_t get_104(const uint32_t* words)
{
    return ((const struct set_jab_combo*) (const void*) words)->disabled;
}

static int64_t get_105(const uint32_t* words)
{
    return ((const struct set_jab_rapid*) (const void*) words)->opcode;
}

static int64_t get_106(const uint32_t* words)
{
    return ((const struct set_jab_rapid*) (const void*) words)->state;
}

static int64_t get_107(const uint32_t* words)
{
    return ((const struct set_dobj_flags*) (const void*) words)->opcode;
}

static int64_t get_108(const uint32_t* words)
{
    return ((const struct set_dobj_flags*) (const void*) words)->idx;
}

static int64_t get_109(const uint32_t* words)
{
    return ((const struct set_dobj_flags*) (const void*) words)->value;
}

static int64_t get_110(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_0*) (const void*) words)->opcode;
}

static int64_t get_111(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_0*) (const void*) words)->idx;
}

static int64_t get_112(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_0*) (const void*) words)->damage;
}

static int64_t get_113(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_1*) (const void*) words)->unk0;
}

static int64_t get_114(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_1*) (const void*) words)->hit_x24;
}

static int64_t get_115(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_1*) (const void*) words)->hit_x28;
}

static int64_t get_116(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_2*) (const void*) words)->hit_x2C;
}

static int64_t get_117(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_2*) (const void*) words)->element;
}

static int64_t get_118(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_2*) (const void*) words)->sfx_severity;
}

static int64_t get_119(const uint32_t* words)
{
    return ((const struct set_throw_hitbox_2*) (const void*) words)->sfx_kind;
}

static int64_t get_120(const uint32_t* words)
{
    return ((const struct unk27*) (const void*) words)->opcode;
}

static int64_t get_121(const uint32_t* words)
{
    return ((const struct unk27*) (const void*) words)->value;
}

static int64_t get_122(const uint32_t* words)
{
    return ((const struct set_article_vis*) (const void*) words)->opcode;
}

static int64_t get_123(const uint32_t* words)
{
    return ((const struct set_article_vis*) (const void*) words)->value;
}

static int64_t get_124(const uint32_t* words)
{
    return ((const struct set_fighter_vis*) (const void*) words)->opcode;
}

static int64_t get_125(const uint32_t* words)
{
    return ((const struct set_fighter_vis*) (const void*) words)->value;
}

static int64_t get_126(const uint32_t* words)
{
    return ((const struct set_tex_anim*) (const void*) words)->opcode;
}

static int64_t get_127(const uint32_t* words)
{
    return ((const struct set_tex_anim*) (const void*) words)->b;
}

static int64_t get_128(const uint32_t* words)
{
    return ((const struct set_tex_anim*) (const void*) words)->idx;
}

static int64_t get_129(const uint32_t* words)
{
    return ((const struct set_tex_anim*) (const void*) words)->idx2;
}

static int64_t get_130(const uint32_t* words)
{
    return ((const struct set_tex_anim*) (const void*) words)->frame;
}

static int64_t get_131(const uint32_t* words)
{
    return ((const struct unk31*) (const void*) words)->opcode;
}

static int64_t get_132(const uint32_t* words)
{
    return ((const struct unk31*) (const void*) words)->unk0;
}

static int64_t get_133(const uint32_t* words)
{
    return ((const struct unk31*) (const void*) words)->unk1;
}

static int64_t get_134(const uint32_t* words)
{
    return ((const struct unk32*) (const void*) words)->opcode;
}

static int64_t get_135(const uint32_t* words)
{
    return ((const struct unk32*) (const void*) words)->unk0;
}

static int64_t get_136(const uint32_t* words)
{
    return ((const struct unk32*) (const void*) words)->unk1;
}

static int64_t get_137(const uint32_t* words)
{
    return ((const struct unk33*) (const void*) words)->opcode;
}

static int64_t get_138(const uint32_t* words)
{
    return ((const struct unk33*) (const void*) words)->unk0;
}

static int64_t get_139(const uint32_t* words)
{
    return ((const struct unk33*) (const void*) words)->unk1;
}

static int64_t get_140(const uint32_t* words)
{
    return ((const struct spawn_gfx_0*) (const void*) words)->opcode;
}

static int64_t get_141(const uint32_t* words)
{
    return ((const struct spawn_gfx_0*) (const void*) words)->boneId;
}

static int64_t get_142(const uint32_t* words)
{
    return ((const struct spawn_gfx_0*) (const void*) words)->useCommonBoneIDs;
}

static int64_t get_143(const uint32_t* words)
{
    return ((const struct spawn_gfx_0*) (const void*) words)->destroyOnStateChange;
}

static int64_t get_144(const uint32_t* words)
{
    return ((const struct spawn_gfx_0*) (const void*) words)->useUnkBone;
}

static int64_t get_145(const uint32_t* words)
{
    return ((const struct spawn_gfx_0*) (const void*) words)->unk1;
}

static int64_t get_146(const uint32_t* words)
{
    return ((const struct spawn_gfx_1*) (const void*) words)->gfxID;
}

static int64_t get_147(const uint32_t* words)
{
    return ((const struct spawn_gfx_1*) (const void*) words)->unkFloat;
}

static int64_t get_148(const uint32_t* words)
{
    return ((const struct spawn_gfx_2*) (const void*) words)->offsetZ;
}

static int64_t get_149(const uint32_t* words)
{
    return ((const struct spawn_gfx_2*) (const void*) words)->offsetY;
}

static int64_t get_150(const uint32_t* words)
{
    return ((const struct spawn_gfx_3*) (const void*) words)->offsetX;
}

static int64_t get_151(const uint32_t* words)
{
    return ((const struct spawn_gfx_3*) (const void*) words)->rangeZ;
}

static int64_t get_152(const uint32_t* words)
{
    return ((const struct spawn_gfx_4*) (const void*) words)->rangeY;
}

static int64_t get_153(const uint32_t* words)
{
    return ((const struct spawn_gfx_4*) (const void*) words)->rangeX;
}

static int64_t get_154(const uint32_t* words)
{
    return ((const struct spawn_hitbox_0*) (const void*) words)->opcode;
}

static int64_t get_155(const uint32_t* words)
{
    return ((const struct spawn_hitbox_0*) (const void*) words)->id;
}

static int64_t get_156(const uint32_t* words)
{
    return ((const struct spawn_hitbox_0*) (const void*) words)->hit_group;
}

static int64_t get_157(const uint32_t* words)
{
    return ((const struct spawn_hitbox_0*) (const void*) words)->only_hit_grabbed;
}

static int64_t get_158(const uint32_t* words)
{
    return ((const struct spawn_hitbox_0*) (const void*) words)->bone;
}

static int64_t get_159(const uint32_t* words)
{
    return ((const struct spawn_hitbox_0*) (const void*) words)->use_common_bone_ids;
}

static int64_t get_160(const uint32_t* words)
{
    return ((const struct spawn_hitbox_0*) (const void*) words)->damage;
}

static int64_t get_161(const uint32_t* words)
{
    return ((const struct spawn_hitbox_1*) (const void*) words)->size;
}

static int64_t get_162(const uint32_t* words)
{
    return ((const struct spawn_hitbox_1*) (const void*) words)->z_offset;
}

static int64_t get_163(const uint32_t* words)
{
    return ((const struct spawn_hitbox_2*) (const void*) words)->y_offset;
}

static int64_t get_164(const uint32_t* words)
{
    return ((const struct spawn_hitbox_2*) (const void*) words)->x_offset;
}

static int64_t get_165(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->angle;
}

static int64_t get_166(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->knockback_growth;
}

static int64_t get_167(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->weight_set_knockback;
}

static int64_t get_168(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->item_hit_interaction;
}

static int64_t get_169(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->ignore_thrown_fighters;
}

static int64_t get_170(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->ignore_fighter_scale;
}

static int64_t get_171(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->clank;
}

static int64_t get_172(const uint32_t* words)
{
    return ((const struct spawn_hitbox_3*) (const void*) words)->rebound;
}

static int64_t get_173(const uint32_t* words)
{
    return ((const struct spawn_hitbox_4*) (const void*) words)->base_knockback;
}

static int64_t get_174(const uint32_t* words)
{
    return ((const struct spawn_hitbox_4*) (const void*) words)->element;
}

static int64_t get_175(const uint32_t* words)
{
    return ((const struct spawn_hitbox_4*) (const void*) words)->shield_damage;
}

static int64_t get_176(const uint32_t* words)
{
    return ((const struct spawn_hitbox_4*) (const void*) words)->hit_sfx_severity;
}

static int64_t get_177(const uint32_t* words)
{
    return ((const struct spawn_hitbox_4*) (const void*) words)->hit_sfx_kind;
}

static int64_t get_178(const uint32_t* words)
{
    return ((const struct spawn_hitbox_4*) (const void*) words)->hit_grounded;
}

static int64_t get_179(const uint32_t* words)
{
    return ((const struct spawn_hitbox_4*) (const void*) words)->hit_aerial;
}

static int64_t get_180(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x0;
}

static int64_t get_181(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b0;
}

static int64_t get_182(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b1;
}

static int64_t get_183(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b2;
}

static int64_t get_184(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b3;
}

static int64_t get_185(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b4;
}

static int64_t get_186(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b5;
}

static int64_t get_187(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b6;
}

static int64_t get_188(const uint32_t* words)
{
    return ((const struct spawn_hitbox_5*) (const void*) words)->x1_b7;
}

static int64_t get_189(const uint32_t* words)
{
    return ((const struct it_create_hitbox_0*) (const void*) words)->opcode;
}

static int64_t get_190(const uint32_t* words)
{
    return ((const struct it_create_hitbox_0*) (const void*) words)->id;
}

static int64_t get_191(const uint32_t* words)
{
    return ((const struct it_create_hitbox_0*) (const void*) words)->hit_group;
}

static int64_t get_192(const uint32_t* words)
{
    return ((const struct it_create_hitbox_0*) (const void*) words)->bone;
}

static int64_t get_193(const uint32_t* words)
{
    return ((const struct it_create_hitbox_0*) (const void*) words)->damage;
}

static int64_t get_194(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->base_knockback;
}

static int64_t get_195(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->element;
}

static int64_t get_196(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->x40_b0;
}

static int64_t get_197(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->shield_damage;
}

static int64_t get_198(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->sfx_severity;
}

static int64_t get_199(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->sfx_kind;
}

static int64_t get_200(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->x40_b3;
}

static int64_t get_201(const uint32_t* words)
{
    return ((const struct it_create_hitbox_4*) (const void*) words)->x40_b2;
}

static int64_t get_202(const uint32_t* words)
{
    return ((const struct spawn_hitbox_skip*) (const void*) words)->xF_b0;
}

static int64_t get_203(const uint32_t* words)
{
    return ((const struct spawn_hitbox_skip*) (const void*) words)->xF_b1;
}

static int64_t get_204(const uint32_t* words)
{
    return ((const struct spawn_hitbox_skip*) (const void*) words)->xF_b2;
}

static int64_t get_205(const uint32_t* words)
{
    return ((const struct spawn_hitbox_skip*) (const void*) words)->xF_b3;
}

static int64_t get_206(const uint32_t* words)
{
    return ((const struct spawn_hitbox_skip*) (const void*) words)->xF_b4;
}

static int64_t get_207(const uint32_t* words)
{
    return ((const struct sound_effect_0*) (const void*) words)->opcode;
}

static int64_t get_208(const uint32_t* words)
{
    return ((const struct sound_effect_0*) (const void*) words)->behavior;
}

static int64_t get_209(const uint32_t* words)
{
    return ((const struct sound_effect_0*) (const void*) words)->unknown;
}

static int64_t get_210(const uint32_t* words)
{
    return ((const struct sound_effect_1*) (const void*) words)->sfx_id;
}

static int64_t get_211(const uint32_t* words)
{
    return ((const struct sound_effect_2*) (const void*) words)->padding;
}

static int64_t get_212(const uint32_t* words)
{
    return ((const struct sound_effect_2*) (const void*) words)->volume;
}

static int64_t get_213(const uint32_t* words)
{
    return ((const struct sound_effect_2*) (const void*) words)->panning;
}

static int64_t get_214(const uint32_t* words)
{
    return ((const struct pseudo_random_sfx_0*) (const void*) words)->opcode;
}

static int64_t get_215(const uint32_t* words)
{
    return ((const struct pseudo_random_sfx_0*) (const void*) words)->volume;
}

static int64_t get_216(const uint32_t* words)
{
    return ((const struct pseudo_random_sfx_0*) (const void*) words)->panning;
}

static int64_t get_217(const uint32_t* words)
{
    return ((const struct pseudo_random_sfx_0*) (const void*) words)->behavior;
}

static int64_t get_218(const uint32_t* words)
{
    return ((const struct pseudo_random_sfx_0*) (const void*) words)->random_range;
}

static int64_t get_219(const uint32_t* words)
{
    return ((const struct pseudo_random_sfx_1*) (const void*) words)->sfx_id;
}

static int64_t get_220(const uint32_t* words)
{
    return ((const struct stage_sfx_0*) (const void*) words)->opcode;
}

static int64_t get_221(const uint32_t* words)
{
    return ((const struct stage_sfx_0*) (const void*) words)->sfx_base;
}

static int64_t get_222(const uint32_t* words)
{
    return ((const struct stage_sfx_0*) (const void*) words)->x2_b0_7;
}

static int64_t get_223(const uint32_t* words)
{
    return ((const struct stage_sfx_0*) (const void*) words)->pitch_select;
}

static int64_t get_224(const uint32_t* words)
{
    return ((const struct stage_sfx_1*) (const void*) words)->sfx_id;
}

static int64_t get_225(const uint32_t* words)
{
    return ((const struct stage_sfx_2*) (const void*) words)->x0_b0_15;
}

static int64_t get_226(const uint32_t* words)
{
    return ((const struct stage_sfx_2*) (const void*) words)->x2_b0_15;
}

static int64_t get_227(const uint32_t* words)
{
    return ((const struct stage_sfx_3*) (const void*) words)->x0_b0_15;
}

static int64_t get_228(const uint32_t* words)
{
    return ((const struct stage_sfx_3*) (const void*) words)->x2_b0_7;
}

static int64_t get_229(const uint32_t* words)
{
    return ((const struct stage_sfx_3*) (const void*) words)->x3_b0_7;
}

static int64_t get_230(const uint32_t* words)
{
    return ((const struct footstep_fx_0*) (const void*) words)->opcode;
}

static int64_t get_231(const uint32_t* words)
{
    return ((const struct footstep_fx_0*) (const void*) words)->boneId;
}

static int64_t get_232(const uint32_t* words)
{
    return ((const struct footstep_fx_0*) (const void*) words)->use_alt_bone;
}

static int64_t get_233(const uint32_t* words)
{
    return ((const struct footstep_fx_0*) (const void*) words)->x1_b7;
}

static int64_t get_234(const uint32_t* words)
{
    return ((const struct footstep_fx_0*) (const void*) words)->x2_b0_7;
}

static int64_t get_235(const uint32_t* words)
{
    return ((const struct footstep_fx_0*) (const void*) words)->x3_b0_7;
}

static int64_t get_236(const uint32_t* words)
{
    return ((const struct unk_fx_0*) (const void*) words)->opcode;
}

static int64_t get_237(const uint32_t* words)
{
    return ((const struct unk_fx_0*) (const void*) words)->x0_b6_7;
}

static int64_t get_238(const uint32_t* words)
{
    return ((const struct unk_fx_0*) (const void*) words)->x1_b0_7;
}

static int64_t get_239(const uint32_t* words)
{
    return ((const struct unk_fx_0*) (const void*) words)->x2_b0_7;
}

static int64_t get_240(const uint32_t* words)
{
    return ((const struct unk_fx_0*) (const void*) words)->x3_b0_7;
}

static int64_t get_241(const uint32_t* words)
{
    return ((const struct smash_charge_0*) (const void*) words)->opcode;
}

static int64_t get_242(const uint32_t* words)
{
    return ((const struct smash_charge_0*) (const void*) words)->charge_frames;
}

static int64_t get_243(const uint32_t* words)
{
    return ((const struct smash_charge_0*) (const void*) words)->charge_rate;
}

static int64_t get_244(const uint32_t* words)
{
    return ((const struct smash_charge_1*) (const void*) words)->color_anim;
}

static int64_t get_245(const uint32_t* words)
{
    return ((const struct smash_charge_1*) (const void*) words)->x1_b0_23;
}

static int64_t get_246(const uint32_t* words)
{
    return ((const struct wind_fx_0*) (const void*) words)->opcode;
}

static int64_t get_247(const uint32_t* words)
{
    return ((const struct wind_fx_0*) (const void*) words)->x0_b6_17;
}

static int64_t get_248(const uint32_t* words)
{
    return ((const struct wind_fx_0*) (const void*) words)->bone;
}

static int64_t get_249(const uint32_t* words)
{
    return ((const struct wind_fx_1*) (const void*) words)->timer;
}

static int64_t get_250(const uint32_t* words)
{
    return ((const struct wind_fx_1*) (const void*) words)->x;
}

static int64_t get_251(const uint32_t* words)
{
    return ((const struct wind_fx_2*) (const void*) words)->y;
}

static int64_t get_252(const uint32_t* words)
{
    return ((const struct wind_fx_2*) (const void*) words)->mag;
}

static int64_t get_253(const uint32_t* words)
{
    return ((const struct wind_fx_3*) (const void*) words)->angle;
}

static int64_t get_254(const uint32_t* words)
{
    return ((const struct wind_fx_3*) (const void*) words)->decay;
}

static const CommandFieldCase cases[] = {
    { "ColorOverlay_x8_t.light_color.r", 0, 24, 8, 0, get_0 },
    { "ColorOverlay_x8_t.light_color.g", 0, 16, 8, 0, get_1 },
    { "ColorOverlay_x8_t.light_color.b", 0, 8, 8, 0, get_2 },
    { "ColorOverlay_x8_t.light_color.a", 0, 0, 8, 0, get_3 },
    { "ColorOverlay_x8_t.light_rot1.unk", 0, 26, 6, 1, get_4 },
    { "ColorOverlay_x8_t.light_rot1.x", 0, 13, 13, 1, get_5 },
    { "ColorOverlay_x8_t.light_rot1.yz", 0, 0, 13, 1, get_6 },
    { "ColorOverlay_x8_t.light_rot2.x0_0", 0, 31, 1, 0, get_7 },
    { "ColorOverlay_x8_t.light_rot2.x0_1", 0, 30, 1, 0, get_8 },
    { "ColorOverlay_x8_t.light_rot2.x0_2", 0, 29, 1, 0, get_9 },
    { "ColorOverlay_x8_t.light_rot2.x0_3", 0, 28, 1, 0, get_10 },
    { "ColorOverlay_x8_t.light_rot2.x0_4", 0, 27, 1, 0, get_11 },
    { "ColorOverlay_x8_t.light_rot2.x0_5", 0, 26, 1, 0, get_12 },
    { "ColorOverlay_x8_t.light_rot2.light_enable", 0, 25, 1, 0, get_13 },
    { "ColorOverlay_x8_t.light_rot2.x0_7", 0, 24, 1, 0, get_14 },
    { "ColorOverlay_x8_t.light_rot2.x", 0, 12, 12, 1, get_15 },
    { "ColorOverlay_x8_t.light_rot2.yz", 0, 0, 12, 1, get_16 },
    { "ColorOverlay_x8_t.unk.unk", 0, 26, 6, 0, get_17 },
    { "ColorOverlay_x8_t.unk.timer", 0, 0, 26, 0, get_18 },
    { "Command_00.code", 0, 26, 6, 0, get_19 },
    { "Command_00.value", 0, 0, 26, 0, get_20 },
    { "Command_02.code", 0, 26, 6, 0, get_21 },
    { "Command_02.value", 0, 0, 26, 0, get_22 },
    { "Command_03.code", 0, 26, 6, 0, get_23 },
    { "Command_03.value", 0, 0, 26, 0, get_24 },
    { "Command_04.x", 0, 0, 32, 0, get_25 },
    { "Command_09.id", 0, 26, 6, 0, get_26 },
    { "Command_09.param_1", 0, 18, 8, 0, get_27 },
    { "Command_09.param_2", 0, 0, 18, 0, get_28 },
    { "unk0.opcode", 0, 26, 6, 0, get_29 },
    { "unk0.unk1", 0, 18, 8, 0, get_30 },
    { "unk0.unk2", 0, 0, 18, 0, get_31 },
    { "unk1.opcode", 0, 26, 6, 0, get_32 },
    { "unk1.unk0", 0, 24, 2, 0, get_33 },
    { "unk1.unk1", 0, 20, 4, 0, get_34 },
    { "unk1.unk2", 0, 19, 1, 0, get_35 },
    { "set_throw_flags.opcode", 0, 26, 6, 0, get_36 },
    { "set_throw_flags.hit_idx", 0, 0, 26, 0, get_37 },
    { "unk3.unk0", 0, 25, 7, 1, get_38 },
    { "unk3.unk1", 0, 0, 25, 1, get_39 },
    { "unk4.opcode", 0, 26, 6, 0, get_40 },
    { "unk4.unk1", 0, 18, 8, 0, get_41 },
    { "unk5.unk0", 0, 18, 14, 1, get_42 },
    { "unk5.unk1", 0, 0, 18, 1, get_43 },
    { "unk6.opcode", 0, 26, 6, 0, get_44 },
    { "unk6.unk1", 0, 25, 1, 0, get_45 },
    { "set_airborne_state.opcode", 0, 26, 6, 0, get_46 },
    { "set_airborne_state.state", 0, 0, 26, 0, get_47 },
    { "unk8.unk0", 0, 0, 32, 1, get_48 },
    { "part_anim.opcode", 0, 26, 6, 1, get_49 },
    { "part_anim.unk1", 0, 19, 7, 1, get_50 },
    { "part_anim.unk2", 0, 12, 7, 1, get_51 },
    { "part_anim.unk3", 0, 0, 12, 0, get_52 },
    { "unk9.unk0", 0, 26, 6, 1, get_53 },
    { "unk9.unk1", 0, 13, 13, 0, get_54 },
    { "unk9.unk2", 0, 0, 13, 0, get_55 },
    { "unk10.unk0", 0, 26, 6, 1, get_56 },
    { "unk10.unk1", 0, 25, 1, 0, get_57 },
    { "unk10.unk2", 0, 13, 12, 0, get_58 },
    { "unk10.unk3", 0, 0, 13, 0, get_59 },
    { "unk11.unk0", 0, 26, 6, 1, get_60 },
    { "unk11.unk1", 0, 0, 26, 0, get_61 },
    { "unk12.unk0", 0, 26, 6, 0, get_62 },
    { "unk12.unk1", 0, 24, 2, 0, get_63 },
    { "unk12.unk2", 0, 14, 10, 0, get_64 },
    { "unk12.unk3", 0, 0, 14, 0, get_65 },
    { "unk13.unk0", 0, 26, 6, 0, get_66 },
    { "unk13.unk1", 0, 18, 8, 0, get_67 },
    { "unk13.unk2", 0, 0, 18, 0, get_68 },
    { "unk14.unk0", 0, 26, 6, 0, get_69 },
    { "unk14.unk1", 0, 18, 8, 0, get_70 },
    { "unk15.unk0", 0, 26, 6, 0, get_71 },
    { "unk15.unk1", 0, 0, 26, 0, get_72 },
    { "unk16.unk0", 0, 26, 6, 0, get_73 },
    { "unk16.unk3", 0, 25, 1, 1, get_74 },
    { "unk16.unk4", 0, 0, 25, 1, get_75 },
    { "unk17.unk0", 0, 26, 6, 0, get_76 },
    { "unk17.unk1", 0, 0, 26, 1, get_77 },
    { "unk18.unk0", 0, 26, 6, 0, get_78 },
    { "unk18.damage_amount", 0, 0, 26, 1, get_79 },
    { "unk19.unk0", 0, 26, 6, 0, get_80 },
    { "unk19.unk1", 0, 0, 26, 0, get_81 },
    { "unk20.unk0", 0, 26, 6, 0, get_82 },
    { "unk20.unk1", 0, 0, 26, 0, get_83 },
    { "unk21.unk0", 0, 26, 6, 0, get_84 },
    { "unk21.unk1", 0, 25, 1, 0, get_85 },
    { "unk21.unk2", 0, 17, 8, 0, get_86 },
    { "set_hitbox_damage.opcdoe", 0, 26, 6, 0, get_87 },
    { "set_hitbox_damage.idx", 0, 23, 3, 0, get_88 },
    { "set_hitbox_damage.value", 0, 0, 23, 0, get_89 },
    { "set_hitbox_scale.opcode", 0, 26, 6, 0, get_90 },
    { "set_hitbox_scale.idx", 0, 23, 3, 0, get_91 },
    { "set_hitbox_scale.value", 0, 0, 23, 0, get_92 },
    { "set_hitbox_x42_b57.opcode", 0, 26, 6, 0, get_93 },
    { "set_hitbox_x42_b57.idx", 0, 2, 24, 0, get_94 },
    { "set_hitbox_x42_b57.type", 0, 1, 1, 0, get_95 },
    { "set_hitbox_x42_b57.value", 0, 0, 1, 0, get_96 },
    { "set_cmd_var.opcode", 0, 26, 6, 0, get_97 },
    { "set_cmd_var.idx", 0, 24, 2, 0, get_98 },
    { "set_cmd_var.value", 0, 0, 24, 0, get_99 },
    { "set_hurt_state.opcode", 0, 26, 6, 0, get_100 },
    { "set_hurt_state.bone_idx", 0, 18, 8, 0, get_101 },
    { "set_hurt_state.state", 0, 0, 18, 0, get_102 },
    { "set_jab_combo.opcode", 0, 26, 6, 0, get_103 },
    { "set_jab_combo.disabled", 0, 0, 26, 0, get_104 },
    { "set_jab_rapid.opcode", 0, 26, 6, 0, get_105 },
    { "set_jab_rapid.state", 0, 0, 26, 0, get_106 },
    { "set_dobj_flags.opcode", 0, 26, 6, 0, get_107 },
    { "set_dobj_flags.idx", 0, 19, 7, 1, get_108 },
    { "set_dobj_flags.value", 0, 0, 19, 1, get_109 },
    { "set_throw_hitbox_0.opcode", 0, 26, 6, 0, get_110 },
    { "set_throw_hitbox_0.idx", 0, 23, 3, 0, get_111 },
    { "set_throw_hitbox_0.damage", 0, 0, 23, 0, get_112 },
    { "set_throw_hitbox_1.unk0", 0, 23, 9, 0, get_113 },
    { "set_throw_hitbox_1.hit_x24", 0, 14, 9, 0, get_114 },
    { "set_throw_hitbox_1.hit_x28", 0, 5, 9, 0, get_115 },
    { "set_throw_hitbox_2.hit_x2C", 0, 23, 9, 0, get_116 },
    { "set_throw_hitbox_2.element", 0, 19, 4, 0, get_117 },
    { "set_throw_hitbox_2.sfx_severity", 0, 16, 3, 0, get_118 },
    { "set_throw_hitbox_2.sfx_kind", 0, 12, 4, 0, get_119 },
    { "unk27.opcode", 0, 26, 6, 0, get_120 },
    { "unk27.value", 0, 0, 26, 0, get_121 },
    { "set_article_vis.opcode", 0, 26, 6, 0, get_122 },
    { "set_article_vis.value", 0, 0, 26, 0, get_123 },
    { "set_fighter_vis.opcode", 0, 26, 6, 0, get_124 },
    { "set_fighter_vis.value", 0, 0, 26, 0, get_125 },
    { "set_tex_anim.opcode", 0, 26, 6, 0, get_126 },
    { "set_tex_anim.b", 0, 25, 1, 0, get_127 },
    { "set_tex_anim.idx", 0, 18, 7, 1, get_128 },
    { "set_tex_anim.idx2", 0, 11, 7, 1, get_129 },
    { "set_tex_anim.frame", 0, 0, 11, 1, get_130 },
    { "unk31.opcode", 0, 26, 6, 0, get_131 },
    { "unk31.unk0", 0, 16, 10, 0, get_132 },
    { "unk31.unk1", 0, 0, 16, 0, get_133 },
    { "unk32.opcode", 0, 26, 6, 0, get_134 },
    { "unk32.unk0", 0, 13, 13, 0, get_135 },
    { "unk32.unk1", 0, 0, 13, 0, get_136 },
    { "unk33.opcode", 0, 26, 6, 0, get_137 },
    { "unk33.unk0", 0, 13, 13, 0, get_138 },
    { "unk33.unk1", 0, 0, 13, 0, get_139 },
    { "spawn_gfx_0.opcode", 0, 26, 6, 0, get_140 },
    { "spawn_gfx_0.boneId", 0, 18, 8, 0, get_141 },
    { "spawn_gfx_0.useCommonBoneIDs", 0, 17, 1, 0, get_142 },
    { "spawn_gfx_0.destroyOnStateChange", 0, 16, 1, 0, get_143 },
    { "spawn_gfx_0.useUnkBone", 0, 15, 1, 0, get_144 },
    { "spawn_gfx_0.unk1", 0, 0, 15, 0, get_145 },
    { "spawn_gfx_1.gfxID", 0, 16, 16, 0, get_146 },
    { "spawn_gfx_1.unkFloat", 0, 0, 16, 0, get_147 },
    { "spawn_gfx_2.offsetZ", 0, 16, 16, 1, get_148 },
    { "spawn_gfx_2.offsetY", 0, 0, 16, 1, get_149 },
    { "spawn_gfx_3.offsetX", 0, 16, 16, 1, get_150 },
    { "spawn_gfx_3.rangeZ", 0, 0, 16, 0, get_151 },
    { "spawn_gfx_4.rangeY", 0, 16, 16, 0, get_152 },
    { "spawn_gfx_4.rangeX", 0, 0, 16, 0, get_153 },
    { "spawn_hitbox_0.opcode", 0, 26, 6, 0, get_154 },
    { "spawn_hitbox_0.id", 0, 23, 3, 0, get_155 },
    { "spawn_hitbox_0.hit_group", 0, 20, 3, 0, get_156 },
    { "spawn_hitbox_0.only_hit_grabbed", 0, 19, 1, 0, get_157 },
    { "spawn_hitbox_0.bone", 0, 11, 8, 0, get_158 },
    { "spawn_hitbox_0.use_common_bone_ids", 0, 10, 1, 0, get_159 },
    { "spawn_hitbox_0.damage", 0, 0, 10, 0, get_160 },
    { "spawn_hitbox_1.size", 0, 16, 16, 0, get_161 },
    { "spawn_hitbox_1.z_offset", 0, 0, 16, 1, get_162 },
    { "spawn_hitbox_2.y_offset", 0, 16, 16, 1, get_163 },
    { "spawn_hitbox_2.x_offset", 0, 0, 16, 1, get_164 },
    { "spawn_hitbox_3.angle", 0, 23, 9, 0, get_165 },
    { "spawn_hitbox_3.knockback_growth", 0, 14, 9, 0, get_166 },
    { "spawn_hitbox_3.weight_set_knockback", 0, 5, 9, 0, get_167 },
    { "spawn_hitbox_3.item_hit_interaction", 0, 4, 1, 0, get_168 },
    { "spawn_hitbox_3.ignore_thrown_fighters", 0, 3, 1, 0, get_169 },
    { "spawn_hitbox_3.ignore_fighter_scale", 0, 2, 1, 0, get_170 },
    { "spawn_hitbox_3.clank", 0, 1, 1, 0, get_171 },
    { "spawn_hitbox_3.rebound", 0, 0, 1, 0, get_172 },
    { "spawn_hitbox_4.base_knockback", 0, 23, 9, 0, get_173 },
    { "spawn_hitbox_4.element", 0, 18, 5, 0, get_174 },
    { "spawn_hitbox_4.shield_damage", 0, 10, 8, 1, get_175 },
    { "spawn_hitbox_4.hit_sfx_severity", 0, 7, 3, 0, get_176 },
    { "spawn_hitbox_4.hit_sfx_kind", 0, 2, 5, 0, get_177 },
    { "spawn_hitbox_4.hit_grounded", 0, 1, 1, 0, get_178 },
    { "spawn_hitbox_4.hit_aerial", 0, 0, 1, 0, get_179 },
    { "spawn_hitbox_5.x0", 0, 24, 8, 0, get_180 },
    { "spawn_hitbox_5.x1_b0", 0, 23, 1, 0, get_181 },
    { "spawn_hitbox_5.x1_b1", 0, 22, 1, 0, get_182 },
    { "spawn_hitbox_5.x1_b2", 0, 21, 1, 0, get_183 },
    { "spawn_hitbox_5.x1_b3", 0, 20, 1, 0, get_184 },
    { "spawn_hitbox_5.x1_b4", 0, 19, 1, 0, get_185 },
    { "spawn_hitbox_5.x1_b5", 0, 18, 1, 0, get_186 },
    { "spawn_hitbox_5.x1_b6", 0, 17, 1, 0, get_187 },
    { "spawn_hitbox_5.x1_b7", 0, 16, 1, 0, get_188 },
    { "it_create_hitbox_0.opcode", 0, 26, 6, 0, get_189 },
    { "it_create_hitbox_0.id", 0, 23, 3, 0, get_190 },
    { "it_create_hitbox_0.hit_group", 0, 20, 3, 0, get_191 },
    { "it_create_hitbox_0.bone", 0, 13, 7, 0, get_192 },
    { "it_create_hitbox_0.damage", 0, 0, 13, 0, get_193 },
    { "it_create_hitbox_4.base_knockback", 0, 23, 9, 0, get_194 },
    { "it_create_hitbox_4.element", 0, 18, 5, 0, get_195 },
    { "it_create_hitbox_4.x40_b0", 0, 17, 1, 0, get_196 },
    { "it_create_hitbox_4.shield_damage", 0, 9, 8, 1, get_197 },
    { "it_create_hitbox_4.sfx_severity", 0, 6, 3, 0, get_198 },
    { "it_create_hitbox_4.sfx_kind", 0, 2, 4, 0, get_199 },
    { "it_create_hitbox_4.x40_b3", 0, 1, 1, 0, get_200 },
    { "it_create_hitbox_4.x40_b2", 0, 0, 1, 0, get_201 },
    { "spawn_hitbox_skip.xF_b0", 3, 7, 1, 0, get_202 },
    { "spawn_hitbox_skip.xF_b1", 3, 6, 1, 0, get_203 },
    { "spawn_hitbox_skip.xF_b2", 3, 5, 1, 0, get_204 },
    { "spawn_hitbox_skip.xF_b3", 3, 4, 1, 0, get_205 },
    { "spawn_hitbox_skip.xF_b4", 3, 3, 1, 0, get_206 },
    { "sound_effect_0.opcode", 0, 26, 6, 0, get_207 },
    { "sound_effect_0.behavior", 0, 18, 8, 0, get_208 },
    { "sound_effect_0.unknown", 0, 0, 18, 0, get_209 },
    { "sound_effect_1.sfx_id", 0, 0, 32, 0, get_210 },
    { "sound_effect_2.padding", 0, 16, 16, 0, get_211 },
    { "sound_effect_2.volume", 0, 8, 8, 0, get_212 },
    { "sound_effect_2.panning", 0, 0, 8, 0, get_213 },
    { "pseudo_random_sfx_0.opcode", 0, 26, 6, 0, get_214 },
    { "pseudo_random_sfx_0.volume", 0, 18, 8, 0, get_215 },
    { "pseudo_random_sfx_0.panning", 0, 10, 8, 0, get_216 },
    { "pseudo_random_sfx_0.behavior", 0, 6, 4, 0, get_217 },
    { "pseudo_random_sfx_0.random_range", 0, 0, 6, 0, get_218 },
    { "pseudo_random_sfx_1.sfx_id", 0, 0, 32, 0, get_219 },
    { "stage_sfx_0.opcode", 0, 26, 6, 0, get_220 },
    { "stage_sfx_0.sfx_base", 0, 16, 10, 0, get_221 },
    { "stage_sfx_0.x2_b0_7", 0, 8, 8, 0, get_222 },
    { "stage_sfx_0.pitch_select", 0, 0, 8, 0, get_223 },
    { "stage_sfx_1.sfx_id", 0, 0, 32, 0, get_224 },
    { "stage_sfx_2.x0_b0_15", 0, 16, 16, 0, get_225 },
    { "stage_sfx_2.x2_b0_15", 0, 0, 16, 0, get_226 },
    { "stage_sfx_3.x0_b0_15", 0, 16, 16, 0, get_227 },
    { "stage_sfx_3.x2_b0_7", 0, 8, 8, 0, get_228 },
    { "stage_sfx_3.x3_b0_7", 0, 0, 8, 0, get_229 },
    { "footstep_fx_0.opcode", 0, 26, 6, 0, get_230 },
    { "footstep_fx_0.boneId", 0, 18, 8, 0, get_231 },
    { "footstep_fx_0.use_alt_bone", 0, 17, 1, 0, get_232 },
    { "footstep_fx_0.x1_b7", 0, 16, 1, 0, get_233 },
    { "footstep_fx_0.x2_b0_7", 0, 8, 8, 0, get_234 },
    { "footstep_fx_0.x3_b0_7", 0, 0, 8, 0, get_235 },
    { "unk_fx_0.opcode", 0, 26, 6, 0, get_236 },
    { "unk_fx_0.x0_b6_7", 0, 24, 2, 0, get_237 },
    { "unk_fx_0.x1_b0_7", 0, 16, 8, 0, get_238 },
    { "unk_fx_0.x2_b0_7", 0, 8, 8, 0, get_239 },
    { "unk_fx_0.x3_b0_7", 0, 0, 8, 0, get_240 },
    { "smash_charge_0.opcode", 0, 26, 6, 0, get_241 },
    { "smash_charge_0.charge_frames", 0, 16, 10, 0, get_242 },
    { "smash_charge_0.charge_rate", 0, 0, 16, 0, get_243 },
    { "smash_charge_1.color_anim", 0, 24, 8, 0, get_244 },
    { "smash_charge_1.x1_b0_23", 0, 0, 24, 0, get_245 },
    { "wind_fx_0.opcode", 0, 26, 6, 0, get_246 },
    { "wind_fx_0.x0_b6_17", 0, 8, 18, 0, get_247 },
    { "wind_fx_0.bone", 0, 0, 8, 0, get_248 },
    { "wind_fx_1.timer", 0, 16, 16, 1, get_249 },
    { "wind_fx_1.x", 0, 0, 16, 1, get_250 },
    { "wind_fx_2.y", 0, 16, 16, 1, get_251 },
    { "wind_fx_2.mag", 0, 0, 16, 1, get_252 },
    { "wind_fx_3.angle", 0, 16, 16, 1, get_253 },
    { "wind_fx_3.decay", 0, 0, 16, 1, get_254 },
};

int melee_host_command_layout_failures(char* message, size_t size);

int melee_host_command_layout_failures(char* message, size_t size)
{
    static const uint32_t values[] = {
        0x00000000U, 0xFFFFFFFFU, 0x55555555U, 0xAAAAAAAAU, 0x89ABCDEFU,
    };
    static const uint32_t backgrounds[] = { 0x00000000U, 0xFFFFFFFFU };
    int failures = 0;
    size_t c;
    size_t v;
    size_t b;

    for (c = 0; c < sizeof(cases) / sizeof(cases[0]); c++) {
        const CommandFieldCase* const field = &cases[c];
        const uint32_t mask = field->width == 32
            ? 0xFFFFFFFFU : (uint32_t) ((1U << field->width) - 1U);
        for (v = 0; v < sizeof(values) / sizeof(values[0]); v++) {
            for (b = 0; b < sizeof(backgrounds) / sizeof(backgrounds[0]); b++) {
                uint32_t words[4];
                const uint32_t value = values[v] & mask;
                int64_t expected = (int64_t) value;
                int64_t got;
                words[0] = words[1] = words[2] = words[3] = backgrounds[b];
                words[field->word] &= ~(mask << field->lsb);
                words[field->word] |= value << field->lsb;
                if (field->is_signed && ((value >> (field->width - 1)) & 1U)) {
                    expected -= (int64_t) 1 << field->width;
                }
                got = field->get(words);
                if (got != expected) {
                    if (failures == 0 && message != NULL && size != 0) {
                        snprintf(message, size,
                                 "%s read %lld where the console reads %lld",
                                 field->name, (long long) got,
                                 (long long) expected);
                    }
                    failures += 1;
                }
            }
        }
    }
    return failures;
}

int melee_host_command_layout_cases(void);

int melee_host_command_layout_cases(void)
{
    return (int) (sizeof(cases) / sizeof(cases[0]));
}
